import * as yup from "yup";
import type { FormFieldProps } from "../model/formFeilds";
import type { SalesType } from "../model/salesType";

export const SalesFormFields: FormFieldProps<SalesType>[] = [
    {
        label: "Department",
        name: "departmentId",
        type: "select",
        required: true,
        size: { sm: 12, md: 6, lg: 6 },
    },
    {
        label: "Brand",
        name: "brandId",
        type: "select",
        required: true,
        size: { sm: 12, md: 6, lg: 6 },
    },
    {
        label: "Category",
        name: "categoryId",
        type: "select",
        required: true,
        size: { sm: 12, md: 6, lg: 6 },
    },
    {
        label: "Sub Category",
        name: "subCategoryId",
        type: "select",
        required: false,
        size: { sm: 12, md: 6, lg: 6 },
    },
    {
        label: "Sub Sub Category",
        name: "subSubCategoryId",
        type: "select",
        required: false,
        size: { sm: 12, md: 6, lg: 6 },
    },
    {
        label: "Sale Type",
        name: "saleTypeId",
        type: "select",
        required: true,
        size: { sm: 12, md: 6, lg: 6 },
    },
    {
        label: "Sale Amount",
        name: "saleAmount",
        type: "number",
        required: true,
        size: { sm: 12, md: 6, lg: 6 },
    },
    {
        label: "Product Price",
        name: "productPrice",
        type: "number",
        required: true,
        size: { sm: 12, md: 6, lg: 6 },
    },
    {
        label: "Tax",
        name: "tax",
        type: "number",
        required: true,
        size: { sm: 12, md: 6, lg: 6 },
    },
    {
        label: "Discount",
        name: "discount",
        type: "number",
        required: true,
        size: { sm: 12, md: 6, lg: 6 },
    },
    {
        label: "Quantity",
        name: "quantity",
        type: "number",
        required: true,
        size: { sm: 12, md: 6, lg: 6 },
    },
    {
        label: "Invoice Number",
        name: "invoiceNumber",
        type: "text",
        required: true,
        size: { sm: 12, md: 6, lg: 6 },
    },
    {
        label: "Item Number",
        name: "itemNumber",
        type: "text",
        required: true,
        size: { sm: 12, md: 6, lg: 6 },
    },
    {
        label: "Notes",
        name: "notes",
        type: "textarea",
        required: false,
        size: { sm: 12, md: 12, lg: 12 },
    },
];

export const salesFormValidationSchema = yup.object().shape({
    departmentId: yup.number().required("Department is required").min(1, "Please select a department"),
    brandId: yup.number().required("Brand is required").min(1, "Please select a brand"),
    categoryId: yup.number().required("Category is required").min(1, "Please select a category"),
    subCategoryId: yup.number().nullable(),
    subSubCategoryId: yup.number().nullable(),
    saleTypeId: yup.number().required("Sale Type is required").min(1, "Please select a sale type"),
    saleAmount: yup.number().required("Sale Amount is required").min(0, "Sale Amount cannot be negative"),
    productPrice: yup.number().required("Product Price is required").min(0, "Product Price cannot be negative"),
    tax: yup.number().required("Tax is required").min(0, "Tax cannot be negative"),
    discount: yup.number().required("Discount is required").min(0, "Discount cannot be negative"),
    quantity: yup.number().required("Quantity is required").min(1, "Quantity must be at least 1"),
    invoiceNumber: yup.string().required("Invoice Number is required"),
    itemNumber: yup.string().required("Item Number is required"),
    notes: yup.string().nullable(),
});