export interface QueryParamsType {
  role?: string;
  categoryId?: string | null | number;
  orderBy?: string;
  page?: number;
  pageSize?: number;
  departmentId?: number;
  postId?: number;
  taskId?: number;
  lectureId?: number | null | string;
  isActive?: string | undefined | boolean;
  storeId?: string;
  countryCodes?: string[];
  storeTypeId?: number;
  challengeAssignmentId?: number;
  creatorId?: number;
  tutorialId?: number | string | undefined;
  groupId?: number | null;
  challengeId?: number | null;
  searchTerm?: string;
  surveyType?: string;
  approvalStatus?: string;
  employeeVoucherId?: number;
  groupName?: string;
  name?: string;
  recurringVoucherId?: number | string;
  validFrom?: number | string;
  designation?: string;
  gender?: string;
  auditType?: string;
  voucherId?: number | string;
  unit?: string;
  employeeId?: number | null | undefined | string;
  voucherTypeId?: string;
  postType?: string[] | string;
  countryCode?: string;
  brandId?: string | number | undefined;
  sopDepartmentId?: string | number | undefined;
  sopCategoryId?: string | number;
  endDate?: string;
  startDate?: string;
  isRedeemed?: boolean | null;
  title?: string;
  id?: number;
  userIdForLike?: number | null;
  userId?: number | string | null;
  jobId?: number | string | null;
  countryId?: number | string | null;
  companyId?: number | string | null;
  locationId?: number | string | null;
  userRole?: string;
  totalRecords?: number | string | null;
  employeeCode?: string | number | null;
  firstName?: number | string | null;
  status?: string;
  createdAt?: string;
  isRecurring?: boolean;
  countryIds?: (number | "select-all")[] | string;
  companyIds?: (number | "select-all")[] | string;
  departmentIds?: (number | "select-all")[] | string;
  locationIds?: (number | "select-all")[] | string;
  surveyId?: number | null;
}
