import { createSlice, type PayloadAction } from "@reduxjs/toolkit";

export interface User {
  employeeID: number;
  firstName: string;
  gender: string;
  dateOfBirth: string;
  personalEmail: string;
  telephoneNo: string;
  displayName: string;
  companyCode: string;
  employeeClassification: string;
  employeeCode: string;
  dateOfJoining: string;
  department: string;
  designationName: string;
  category: string;
  storeCode: string;
  brandCode: string;
  country: string;
  retailCountry: string;
  resignationDate: string | null;
  createdDateTime: string;
  branch: string;
}

export interface Sale {
  countryCode: string;
  storeID: string;
  date: string;
  brandID: string;
  category: string;
  employeeNumber: string;
  amount: number;
  quantity: number;
  createdTime: string;
  department: string;
  subCategory: string;
  subSubCategory: string;
  discount: number;
  tax: number;
  invoiceNumber: string;
  itemNumber: string;
}

export interface Attendance {
  countryCode: string;
  storeID: string;
  employeeNumber: string;
  date: string;
  dayType: string;
  timeIn: string | null;
  timeOut: string | null;
  leaveType: string | null;
  exceptionStatus: string;
  companyID: number;
  subCompanyID: number;
  createdTime: string;
  actualWorkHours: number | null;
  attendanceID: number;
  remarks: string | null;
  shiftCode: string;
}

export interface Leave {
  employeeNumber: string;
  date: string;
  leaveTypeCode: string;
  leaveUnits: number;
  leaveTypeLongDescription: string;
  leaveReason: string | null;
  remarks: string | null;
  leaveID: number;
  countryCode: string;
  storeID: string;
  createdTime: string;
  leaveApplnNumber: number;
}

export interface StoreTarget {
  id: number;
  brandId: number;
  storeId: number;
  year: number;
  month: number;
  roleId: string;
  targetAmount: number;
  storeKPITargetBraPenetration: number;
  storeKPIAchievementBraPenetration: number;
  storeTargetAchievement: number;
  status: number;
}

export interface TestDataState {
  year: number;
  month: number;
  storeId: number;
  users: User[];
  sales: Sale[];
  attendance: Attendance[];
  leaves: Leave[];
  storeTargets: StoreTarget[];
  workflowJson: string;
}

const initialState: TestDataState = {
  year: 2024,
  month: 10,
  storeId: 1,
  workflowJson: "",
  users: [
    {
      employeeID: 86935,
      firstName: "AAT RATNA SARI",
      gender: "FEMALE",
      dateOfBirth: "9/17/1994",
      personalEmail: "ratnasariaat20@gmail.com",
      telephoneNo: "82221977739",
      displayName: "RATNA",
      companyCode: "DLX",
      employeeClassification: "FIXED TERM CONTRACT",
      employeeCode: "V017470",
      dateOfJoining: "12/28/2023",
      department: "VICTORIA'S SECRET BEAUTY & ACCESSORIES",
      designationName: "RETAIL ASSOCIATE",
      category: "RETAIL",
      storeCode: "I17",
      brandCode: "VCS",
      country: "INDONESIA",
      retailCountry: "INDONESIA",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "JKT-LIPPO MALL PURI",
    },
    {
      employeeID: 86936,
      firstName: "ABANG MUHAMMAD AIZAT AZRI BIN RABAIEE",
      gender: "MALE",
      dateOfBirth: "11/3/1995",
      personalEmail: "aizatrabaiee@gmail.com",
      telephoneNo: "128202391",
      displayName: "AIZAT AZRI",
      companyCode: "NGC",
      employeeClassification: "PERMANENT",
      employeeCode: "V020077",
      dateOfJoining: "10/28/2024",
      department: "BATH & BODY WORKS",
      designationName: "RETAIL ASSOCIATE",
      category: "RETAIL",
      storeCode: "N69",
      brandCode: "BBW",
      country: "MALAYSIA",
      retailCountry: "MALAYSIA",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "SWK-THE SPRING KUCHING",
    },
    {
      employeeID: 86941,
      firstName: "ABDUL GANI",
      gender: "MALE",
      dateOfBirth: "4/3/1996",
      personalEmail: "abdulganytgi267@gmail.com",
      telephoneNo: "81779044079",
      displayName: "GANI",
      companyCode: "DLX",
      employeeClassification: "PERMANENT",
      employeeCode: "V010644",
      dateOfJoining: "10/25/2021",
      department: "VICTORIA'S SECRET FULL ASSORTMENT",
      designationName: "RETAIL ASSOCIATE",
      category: "RETAIL",
      storeCode: "I41",
      brandCode: "VCS",
      country: "INDONESIA",
      retailCountry: "INDONESIA",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "JKT-SENAYAN CITY",
    },
    {
      employeeID: 86943,
      firstName: "ABDUL MUHAIMIN BIN AHMAD",
      gender: "MALE",
      dateOfBirth: "11/24/1992",
      personalEmail: "muhaimina678@gmail.com",
      telephoneNo: "93926426",
      displayName: "MUHAIMIN",
      companyCode: "LVS",
      employeeClassification: "PERMANENT",
      employeeCode: "V015206",
      dateOfJoining: "6/6/2023",
      department: "BATH & BODY WORKS",
      designationName: "SUPERVISOR",
      category: "RETAIL",
      storeCode: "S68",
      brandCode: "BBW",
      country: "SINGAPORE",
      retailCountry: "SINGAPORE",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "CAUSEWAY POINT",
    },
    {
      employeeID: 86945,
      firstName: "ABDUL MUZHAFAR BIN MAT",
      gender: "MALE",
      dateOfBirth: "2/4/1993",
      personalEmail: "MUZCR717@GMAIL.COM",
      telephoneNo: "016-8517904",
      displayName: "MUZ",
      companyCode: "NGC",
      employeeClassification: "PERMANENT",
      employeeCode: "V008007",
      dateOfJoining: "10/5/2019",
      department: "BATH & BODY WORKS",
      designationName: "SUPERVISOR",
      category: "RETAIL",
      storeCode: "K16",
      brandCode: "BBW",
      country: "MALAYSIA",
      retailCountry: "MALAYSIA",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "SWK-VIVA CITY MALL KUCHING",
    },
    {
      employeeID: 86946,
      firstName: "ABDUL QAYYUM BIN SAZALI",
      gender: "MALE",
      dateOfBirth: "8/4/1999",
      personalEmail: "qayyum6267@gmail.com",
      telephoneNo: "011-25889802",
      displayName: "QAYYUM",
      companyCode: "CVL",
      employeeClassification: "PERMANENT",
      employeeCode: "V015482",
      dateOfJoining: "7/3/2023",
      department: "VICTORIA'S SECRET BEAUTY & ACCESSORIES",
      designationName: "RETAIL ASSOCIATE",
      category: "RETAIL",
      storeCode: "N91",
      brandCode: "VCS",
      country: "MALAYSIA",
      retailCountry: "MALAYSIA",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "SGR-FLYING EMPORIUM KLIA",
    },
    {
      employeeID: 86947,
      firstName: "ABDULLAH ALIF BIN OMARAMIYAH",
      gender: "MALE",
      dateOfBirth: "11/9/1990",
      personalEmail: "abdullahalif.omaramiyah@gmail.com",
      telephoneNo: "013-8268056",
      displayName: "ALIF",
      companyCode: "NGC",
      employeeClassification: "PERMANENT",
      employeeCode: "V010590",
      dateOfJoining: "4/27/2021",
      department: "VICTORIA'S SECRET BEAUTY & ACCESSORIES",
      designationName: "ASSISTANT STORE MANAGER",
      category: "RETAIL",
      storeCode: "N89",
      brandCode: "VCS",
      country: "MALAYSIA",
      retailCountry: "MALAYSIA",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "SWK-THE SPRING KUCHING",
    },
    {
      employeeID: 86948,
      firstName: "ABEGAIL OQUENDO ASCANO",
      gender: "FEMALE",
      dateOfBirth: "11/28/1992",
      personalEmail: "abegail11281992@gmail.com",
      telephoneNo: "9674020274",
      displayName: "ABEGAIL",
      companyCode: "PBI",
      employeeClassification: "PERMANENT",
      employeeCode: "V018201",
      dateOfJoining: "3/23/2025",
      department: "VICTORIA'S SECRET BEAUTY & ACCESSORIES",
      designationName: "RETAIL ASSOCIATE",
      category: "RETAIL",
      storeCode: "P08",
      brandCode: "VCS",
      country: "PHILIPPINES",
      retailCountry: "PHILIPPINES",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "MNL-SM STA. MESA",
    },
    {
      employeeID: 86950,
      firstName: "ABIGAIL GALAMAY VALENZUELA",
      gender: "FEMALE",
      dateOfBirth: "6/25/1994",
      personalEmail: "gailvalenzuela251828@gmail.com",
      telephoneNo: "9398300998",
      displayName: "ABIGAIL",
      companyCode: "PBI",
      employeeClassification: "FIXED TERM CONTRACT",
      employeeCode: "V019559",
      dateOfJoining: "9/2/2024",
      department: "VICTORIA'S SECRET BEAUTY & ACCESSORIES",
      designationName: "RETAIL ASSOCIATE",
      category: "RETAIL",
      storeCode: "P13",
      brandCode: "VCS",
      country: "PHILIPPINES",
      retailCountry: "PHILIPPINES",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "MNL - SM CITY NORTH EDSA",
    },
    {
      employeeID: 86951,
      firstName: "ACHARA POLCHAI",
      gender: "FEMALE",
      dateOfBirth: "8/15/1985",
      personalEmail: "ACHARA.POLCHAI@GMAIL.COM",
      telephoneNo: "909049740",
      displayName: "AMP",
      companyCode: "FKD",
      employeeClassification: "PERMANENT",
      employeeCode: "V020975",
      dateOfJoining: "1/15/2025",
      department: "VICTORIA'S SECRET FULL ASSORTMENT",
      designationName: "CUSTOMER EXPERIENCE MANAGER",
      category: "RETAIL",
      storeCode: "T68",
      brandCode: "VCS",
      country: "THAILAND",
      retailCountry: "THAILAND",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "BKK-MEGABANGNA",
    },
    {
      employeeID: 86952,
      firstName: "ACOSTA ANDREA HSU",
      gender: "FEMALE",
      dateOfBirth: "4/24/2004",
      personalEmail: "andreaacostahsu@gmail.com",
      telephoneNo: "54091660",
      displayName: "YEE CHING",
      companyCode: "VVL",
      employeeClassification: "PART TIME",
      employeeCode: "V012875",
      dateOfJoining: "9/8/2022",
      department: "BATH & BODY WORKS",
      designationName: "PART TIMER",
      category: "RETAIL",
      storeCode: "H03",
      brandCode: "BBW",
      country: "HONG KONG",
      retailCountry: "HONG KONG",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "FESTIVAL WALK",
    },
    {
      employeeID: 86953,
      firstName: "ACTING SUB.LT THIDARAT BOONTHAM",
      gender: "FEMALE",
      dateOfBirth: "10/5/1991",
      personalEmail: "THIDARAT.BOONTHAM2534@GMAIL.COM",
      telephoneNo: "985094346",
      displayName: "FERN",
      companyCode: "FKD",
      employeeClassification: "PERMANENT",
      employeeCode: "V005809",
      dateOfJoining: "3/15/2023",
      department: "VICTORIA'S SECRET FULL ASSORTMENT",
      designationName: "SENIOR RETAIL ASSOCIATE",
      category: "RETAIL",
      storeCode: "T43",
      brandCode: "VCS",
      country: "THAILAND",
      retailCountry: "THAILAND",
      resignationDate: "9/5/2025",
      createdDateTime: "45:21.8",
      branch: "BKK-CENTRAL WORLD",
    },
    {
      employeeID: 86965,
      firstName: "ADE LIANA",
      gender: "FEMALE",
      dateOfBirth: "5/28/1998",
      personalEmail: "adelianaadel544@gmail.com",
      telephoneNo: "895711000000",
      displayName: "ADE",
      companyCode: "DLX",
      employeeClassification: "FIXED TERM CONTRACT",
      employeeCode: "V019404",
      dateOfJoining: "8/25/2024",
      department: "BATH & BODY WORKS",
      designationName: "RETAIL ASSOCIATE",
      category: "RETAIL",
      storeCode: "I61",
      brandCode: "BBW",
      country: "INDONESIA",
      retailCountry: "INDONESIA",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "BPP-PENTACITY MALL BALIKPAPAN",
    },
    {
      employeeID: 86966,
      firstName: "ADELINE CHEAH HSU LYNN",
      gender: "FEMALE",
      dateOfBirth: "6/18/2005",
      personalEmail: "adelinecheah111@gmail.com",
      telephoneNo: "011-51168350",
      displayName: "ADELINE",
      companyCode: "NGC",
      employeeClassification: "PERMANENT",
      employeeCode: "V022542",
      dateOfJoining: "7/14/2025",
      department: "VICTORIA'S SECRET FULL ASSORTMENT",
      designationName: "RETAIL ASSOCIATE",
      category: "RETAIL",
      storeCode: "L47",
      brandCode: "VCS",
      country: "MALAYSIA",
      retailCountry: "MALAYSIA",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "KUL-MID VALLEY",
    },
    {
      employeeID: 86967,
      firstName: "ADELLIA MUTIARA KUSUMO",
      gender: "FEMALE",
      dateOfBirth: "7/5/2000",
      personalEmail: "adelliamutiara11@gmail.com",
      telephoneNo: "85156987017",
      displayName: "ADELLIA",
      companyCode: "DLX",
      employeeClassification: "FIXED TERM CONTRACT",
      employeeCode: "V016460",
      dateOfJoining: "10/13/2023",
      department: "BATH & BODY WORKS",
      designationName: "RETAIL ASSOCIATE",
      category: "RETAIL",
      storeCode: "I65",
      brandCode: "BBW",
      country: "INDONESIA",
      retailCountry: "INDONESIA",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "JKT-PONDOK INDAH MALL",
    },
    {
      employeeID: 86968,
      firstName: "ADHA MULIA",
      gender: "FEMALE",
      dateOfBirth: "7/13/1989",
      personalEmail: "adha.mulia13@gmail.com",
      telephoneNo: "87735287011",
      displayName: "ADHA",
      companyCode: "DLX",
      employeeClassification: "PERMANENT",
      employeeCode: "V003374",
      dateOfJoining: "11/16/2015",
      department: "BATH & BODY WORKS",
      designationName: "SENIOR RETAIL ASSOCIATE",
      category: "RETAIL",
      storeCode: "I65",
      brandCode: "BBW",
      country: "INDONESIA",
      retailCountry: "INDONESIA",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "JKT-PONDOK INDAH MALL",
    },
    {
      employeeID: 86973,
      firstName: "ADISTA PERDANA",
      gender: "MALE",
      dateOfBirth: "5/4/1986",
      personalEmail: "adista.perdana@valiram.com",
      telephoneNo: "8993883688",
      displayName: "ADISTA",
      companyCode: "DLX",
      employeeClassification: "PERMANENT",
      employeeCode: "V003536",
      dateOfJoining: "5/15/2019",
      department: "BATH & BODY WORKS",
      designationName: "STORE MANAGER",
      category: "RETAIL",
      storeCode: "I22",
      brandCode: "BBW",
      country: "INDONESIA",
      retailCountry: "INDONESIA",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "SBY-PLAZA TUNJUNGAN",
    },
    {
      employeeID: 86974,
      firstName: "ADISTRIYA BIN MOHTAR",
      gender: "MALE",
      dateOfBirth: "9/24/1984",
      personalEmail: "adistriya.mohtar@valiram.com",
      telephoneNo: "0",
      displayName: "ADISTRIYA",
      companyCode: "NGC",
      employeeClassification: "PERMANENT",
      employeeCode: "V005169",
      dateOfJoining: "3/8/2018",
      department: "BATH & BODY WORKS",
      designationName: "STORE MANAGER",
      category: "RETAIL",
      storeCode: "L55",
      brandCode: "BBW",
      country: "MALAYSIA",
      retailCountry: "MALAYSIA",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "JHR-MID VALLEY SOUTHKEY MEGAMALL",
    },
    {
      employeeID: 86976,
      firstName: "ADRIANA NAFISAH BINTI NASRIZAL",
      gender: "FEMALE",
      dateOfBirth: "11/5/2003",
      personalEmail: "adriana.nasrizal@yahoo.com",
      telephoneNo: "017-4466421",
      displayName: "ADRIANA",
      companyCode: "NGC",
      employeeClassification: "PERMANENT",
      employeeCode: "V022487",
      dateOfJoining: "7/14/2025",
      department: "BATH & BODY WORKS",
      designationName: "RETAIL ASSOCIATE",
      category: "RETAIL",
      storeCode: "O69",
      brandCode: "BBW",
      country: "MALAYSIA",
      retailCountry: "MALAYSIA",
      resignationDate: "9/14/2025",
      createdDateTime: "45:21.8",
      branch: "KUL - TUN RAZAK EXCHANGE",
    },
    {
      employeeID: 86977,
      firstName: "ADZMARR BIN MCKARTNY",
      gender: "MALE",
      dateOfBirth: "10/25/1996",
      personalEmail: "adzmarrm@gmail.com",
      telephoneNo: "011-36432500",
      displayName: "ADZMARR",
      companyCode: "NGC",
      employeeClassification: "PERMANENT",
      employeeCode: "V016978",
      dateOfJoining: "11/14/2023",
      department: "VICTORIA'S SECRET FULL ASSORTMENT",
      designationName: "SENIOR CASHIER",
      category: "RETAIL",
      storeCode: "O60",
      brandCode: "VCS",
      country: "MALAYSIA",
      retailCountry: "MALAYSIA",
      resignationDate: null,
      createdDateTime: "45:21.8",
      branch: "KUL - TUN RAZAK EXCHANGE",
    },
  ],
  sales: [
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "ACCESSORIES",
      employeeNumber: "BBW",
      amount: 16.37,
      quantity: 1,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "ACCESSORIES-PCB",
      subSubCategory: "3W DECOR",
      discount: 42,
      tax: 1.64,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "ACCESSORIES",
      employeeNumber: "BBW",
      amount: 53.81,
      quantity: 3,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "ACCESSORIES-PCB",
      subSubCategory: "3W SLEEVES",
      discount: 12.8,
      tax: 5.39,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "ACCESSORIES",
      employeeNumber: "BBW",
      amount: 26.36,
      quantity: 6,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "ACCESSORIES-PCB",
      subSubCategory: "CORE-PCB",
      discount: 0,
      tax: 2.62,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "ACCESSORIES",
      employeeNumber: "BBW",
      amount: 13.04,
      quantity: 6,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "ACCESSORIES-PCB",
      subSubCategory: "SPONGES-PCB",
      discount: 33.6,
      tax: 1.32,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "BEAUTY",
      employeeNumber: "BBW",
      amount: 33.8,
      quantity: 3,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "BODY CARE-PCB",
      subSubCategory: "CLEANSER BODY CREAM",
      discount: 73.69,
      tax: 3.38,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "BEAUTY",
      employeeNumber: "BBW",
      amount: 26.62,
      quantity: 3,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "BODY CARE-PCB",
      subSubCategory: "CLEANSER BODY GEL",
      discount: 81.58,
      tax: 2.66,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "BEAUTY",
      employeeNumber: "BBW",
      amount: 69.87,
      quantity: 13,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "BODY CARE-PCB",
      subSubCategory: "FOAM SOAP",
      discount: 144.48,
      tax: 6.99,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "BEAUTY",
      employeeNumber: "BBW",
      amount: 9.26,
      quantity: 2,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "BODY CARE-PCB",
      subSubCategory: "GEL SOAP",
      discount: 23.74,
      tax: 0.92,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "BEAUTY",
      employeeNumber: "BBW",
      amount: 89.94,
      quantity: 21,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "BODY CARE-PCB",
      subSubCategory: "MINI SANITIZER",
      discount: 25.97,
      tax: 8.98,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "BEAUTY",
      employeeNumber: "BBW",
      amount: 8.72,
      quantity: 2,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "BODY CARE-PCB",
      subSubCategory: "MINI SHOWER GEL",
      discount: 22.34,
      tax: 0.86,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "BEAUTY",
      employeeNumber: "BBW",
      amount: 176.82,
      quantity: 12,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "BODY CARE-PCB",
      subSubCategory: "MOIST. BODY CREAM",
      discount: 278.91,
      tax: 17.65,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "BEAUTY",
      employeeNumber: "BBW",
      amount: 37.37,
      quantity: 4,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "BODY CARE-PCB",
      subSubCategory: "MOIST. BODY LOTION",
      discount: 106.71,
      tax: 3.74,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "BEAUTY",
      employeeNumber: "BBW",
      amount: 36.2,
      quantity: 4,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "BODY CARE-PCB",
      subSubCategory: "MOIST. HAND CREAM",
      discount: 0,
      tax: 3.6,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "BEAUTY",
      employeeNumber: "BBW",
      amount: 4.89,
      quantity: 3,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "BODY CARE-PCB",
      subSubCategory: "MOISTPB",
      discount: 12.5,
      tax: 0.48,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "BEAUTY",
      employeeNumber: "BBW",
      amount: 16.23,
      quantity: 3,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "BODY CARE-PCB",
      subSubCategory: "SPRAY SANITIZER",
      discount: 0,
      tax: 1.62,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "BEAUTY",
      employeeNumber: "BBW",
      amount: 0,
      quantity: 10,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "FRAGRANCE-PCB",
      subSubCategory: "EAU DE PARFUM-JUICE",
      discount: 50,
      tax: 0,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "BEAUTY",
      employeeNumber: "BBW",
      amount: 77.23,
      quantity: 1,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "FRAGRANCE-PCB",
      subSubCategory: "EAU DE TOILETTE-JUIC",
      discount: 0,
      tax: 7.72,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "BEAUTY",
      employeeNumber: "BBW",
      amount: 15.41,
      quantity: 1,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "FRAGRANCE-PCB",
      subSubCategory: "MINI FRAGRANCE MIST",
      discount: 0,
      tax: 1.54,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "BEAUTY",
      employeeNumber: "BBW",
      amount: 265.2,
      quantity: 11,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "FRAGRANCE-PCB",
      subSubCategory: "MIST/SPLASH - JUICE",
      discount: 133.75,
      tax: 26.5,
      invoiceNumber: "",
      itemNumber: "",
    },
    {
      countryCode: "AU",
      storeID: "A02",
      date: "7/1/2025",
      brandID: "BBW",
      category: "BEAUTY",
      employeeNumber: "BBW",
      amount: 13.64,
      quantity: 1,
      createdTime: "2025-08-03 11:31:54.063",
      department: "LADIES",
      subCategory: "FRAGRANCE-PCB",
      subSubCategory: "SHIMMER MIST",
      discount: 22.95,
      tax: 1.36,
      invoiceNumber: "",
      itemNumber: "",
    },
  ],
  attendance: [
    {
      countryCode: "HK",
      storeID: "H03",
      employeeNumber: "V012202",
      date: "6/29/2025",
      dayType: "Working Day",
      timeIn: "12:55:00",
      timeOut: "21:00:00",
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: 7.08,
      attendanceID: 1266697,
      remarks: null,
      shiftCode: "A06-01-01",
    },
    {
      countryCode: "HK",
      storeID: "H22",
      employeeNumber: "V012203",
      date: "6/29/2025",
      dayType: "OFF Day",
      timeIn: null,
      timeOut: null,
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: null,
      attendanceID: 1266698,
      remarks: null,
      shiftCode: "OFF",
    },
    {
      countryCode: "HK",
      storeID: "H26",
      employeeNumber: "V012208",
      date: "6/29/2025",
      dayType: "Working Day",
      timeIn: "9:52:00",
      timeOut: "19:09:00",
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: 8.28,
      attendanceID: 1266699,
      remarks: null,
      shiftCode: "MD08-01-02",
    },
    {
      countryCode: "HK",
      storeID: "H03",
      employeeNumber: "V012202",
      date: "6/7/2025",
      dayType: "Working Day",
      timeIn: "13:34:00",
      timeOut: "22:11:00",
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: 7.62,
      attendanceID: 1266700,
      remarks: null,
      shiftCode: "A06-01-01",
    },
    {
      countryCode: "HK",
      storeID: "H03",
      employeeNumber: "V012202",
      date: "6/26/2025",
      dayType: "Working Day",
      timeIn: "13:02:00",
      timeOut: "21:54:00",
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: 7.87,
      attendanceID: 1266701,
      remarks: null,
      shiftCode: "A06-01-01",
    },
    {
      countryCode: "HK",
      storeID: "H22",
      employeeNumber: "V012203",
      date: "6/7/2025",
      dayType: "OFF Day",
      timeIn: null,
      timeOut: null,
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: null,
      attendanceID: 1266702,
      remarks: null,
      shiftCode: "OFF",
    },
    {
      countryCode: "HK",
      storeID: "H23",
      employeeNumber: "V018749",
      date: "6/6/2025",
      dayType: "Working Day",
      timeIn: null,
      timeOut: null,
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: null,
      attendanceID: 1266703,
      remarks: null,
      shiftCode: "M08-01-03",
    },
    {
      countryCode: "HK",
      storeID: "H04",
      employeeNumber: "V021434",
      date: "6/29/2025",
      dayType: "Working Day",
      timeIn: "10:57:00",
      timeOut: "20:00:00",
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: 8.05,
      attendanceID: 1266704,
      remarks: null,
      shiftCode: "MD08-01-03",
    },
    {
      countryCode: "HK",
      storeID: "H26",
      employeeNumber: "V012204",
      date: "6/6/2025",
      dayType: "Working Day",
      timeIn: "9:54:00",
      timeOut: "19:09:00",
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: 8.25,
      attendanceID: 1266705,
      remarks: null,
      shiftCode: "MD08-01-02",
    },
    {
      countryCode: "HK",
      storeID: "H04",
      employeeNumber: "V012207",
      date: "6/6/2025",
      dayType: "OFF Day",
      timeIn: null,
      timeOut: null,
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: null,
      attendanceID: 1266706,
      remarks: null,
      shiftCode: "OFF",
    },
    {
      countryCode: "HK",
      storeID: "H04",
      employeeNumber: "V021434",
      date: "6/6/2025",
      dayType: "OFF Day",
      timeIn: null,
      timeOut: null,
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: null,
      attendanceID: 1266707,
      remarks: null,
      shiftCode: "OFF",
    },
    {
      countryCode: "HK",
      storeID: "H22",
      employeeNumber: "V021771",
      date: "6/6/2025",
      dayType: "OFF Day",
      timeIn: null,
      timeOut: null,
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: null,
      attendanceID: 1266708,
      remarks: null,
      shiftCode: "OFF",
    },
    {
      countryCode: "HK",
      storeID: "H24",
      employeeNumber: "V020552",
      date: "6/6/2025",
      dayType: "OFF Day",
      timeIn: null,
      timeOut: null,
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: null,
      attendanceID: 1266709,
      remarks: null,
      shiftCode: "OFF",
    },
    {
      countryCode: "HK",
      storeID: "H04",
      employeeNumber: "V021409",
      date: "6/6/2025",
      dayType: "Working Day",
      timeIn: "10:47:00",
      timeOut: "20:01:00",
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: 8.23,
      attendanceID: 1266710,
      remarks: null,
      shiftCode: "MD08-01-03",
    },
    {
      countryCode: "HK",
      storeID: "H26",
      employeeNumber: "V012204",
      date: "6/29/2025",
      dayType: "Working Day",
      timeIn: "9:54:00",
      timeOut: "19:03:00",
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: 8.15,
      attendanceID: 1266711,
      remarks: null,
      shiftCode: "MD08-01-02",
    },
    {
      countryCode: "HK",
      storeID: "H04",
      employeeNumber: "V012207",
      date: "6/29/2025",
      dayType: "OFF Day",
      timeIn: null,
      timeOut: null,
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: null,
      attendanceID: 1266712,
      remarks: null,
      shiftCode: "OFF",
    },
    {
      countryCode: "HK",
      storeID: "H26",
      employeeNumber: "V014384",
      date: "6/6/2025",
      dayType: "OFF Day",
      timeIn: null,
      timeOut: null,
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: null,
      attendanceID: 1266713,
      remarks: null,
      shiftCode: "OFF",
    },
    {
      countryCode: "HK",
      storeID: "H22",
      employeeNumber: "V021771",
      date: "6/29/2025",
      dayType: "OFF Day",
      timeIn: null,
      timeOut: null,
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: null,
      attendanceID: 1266714,
      remarks: null,
      shiftCode: "OFF",
    },
    {
      countryCode: "HK",
      storeID: "H24",
      employeeNumber: "V020068",
      date: "6/29/2025",
      dayType: "OFF Day",
      timeIn: null,
      timeOut: null,
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: null,
      attendanceID: 1266715,
      remarks: null,
      shiftCode: "OFF",
    },
    {
      countryCode: "HK",
      storeID: "H04",
      employeeNumber: "V021409",
      date: "6/29/2025",
      dayType: "Working Day",
      timeIn: "12:11:00",
      timeOut: "21:30:00",
      leaveType: null,
      exceptionStatus: "OK",
      companyID: 1,
      subCompanyID: 20,
      createdTime: "41:19.7",
      actualWorkHours: 8.32,
      attendanceID: 1266716,
      remarks: null,
      shiftCode: "MD-08-90",
    },
  ],
  leaves: [
    {
      employeeNumber: "V000058",
      date: "7/27/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "VACATION",
      remarks: "Submitted",
      leaveID: 182902,
      countryCode: "MY",
      storeID: "K74",
      createdTime: "00:02.3",
      leaveApplnNumber: 274,
    },
    {
      employeeNumber: "V000058",
      date: "7/28/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "VACATION",
      remarks: "Submitted",
      leaveID: 182903,
      countryCode: "MY",
      storeID: "K74",
      createdTime: "00:02.3",
      leaveApplnNumber: 274,
    },
    {
      employeeNumber: "V000058",
      date: "6/6/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "VACATION",
      remarks: null,
      leaveID: 138907,
      countryCode: "MY",
      storeID: "K74",
      createdTime: "40:59.0",
      leaveApplnNumber: 273,
    },
    {
      employeeNumber: "V000131",
      date: "7/28/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "VACATION",
      remarks: "Submitted",
      leaveID: 183024,
      countryCode: "SG",
      storeID: "S66",
      createdTime: "00:02.3",
      leaveApplnNumber: 233,
    },
    {
      employeeNumber: "V000131",
      date: "7/29/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "VACATION",
      remarks: "Submitted",
      leaveID: 183025,
      countryCode: "SG",
      storeID: "S66",
      createdTime: "00:02.3",
      leaveApplnNumber: 233,
    },
    {
      employeeNumber: "V000131",
      date: "7/30/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "VACATION",
      remarks: "Submitted",
      leaveID: 183026,
      countryCode: "SG",
      storeID: "S66",
      createdTime: "00:02.3",
      leaveApplnNumber: 233,
    },
    {
      employeeNumber: "V000131",
      date: "7/31/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "VACATION",
      remarks: "Submitted",
      leaveID: 183027,
      countryCode: "SG",
      storeID: "S66",
      createdTime: "00:02.3",
      leaveApplnNumber: 233,
    },
    {
      employeeNumber: "V000149",
      date: "7/24/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "NOT APPLICABLE",
      remarks: "Submitted",
      leaveID: 182685,
      countryCode: "SG",
      storeID: "S39",
      createdTime: "00:02.3",
      leaveApplnNumber: 150,
    },
    {
      employeeNumber: "V000149",
      date: "7/23/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "NOT APPLICABLE",
      remarks: "Submitted",
      leaveID: 182684,
      countryCode: "SG",
      storeID: "S39",
      createdTime: "00:02.3",
      leaveApplnNumber: 150,
    },
    {
      employeeNumber: "V000149",
      date: "7/22/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "NOT APPLICABLE",
      remarks: "Submitted",
      leaveID: 182683,
      countryCode: "SG",
      storeID: "S39",
      createdTime: "00:02.3",
      leaveApplnNumber: 150,
    },
    {
      employeeNumber: "V000149",
      date: "7/20/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "NOT APPLICABLE",
      remarks: "Submitted",
      leaveID: 182682,
      countryCode: "SG",
      storeID: "S39",
      createdTime: "00:02.3",
      leaveApplnNumber: 149,
    },
    {
      employeeNumber: "V000149",
      date: "7/19/2025",
      leaveTypeCode: "LVBDL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Birthday Leave",
      leaveReason: null,
      remarks: "Submitted",
      leaveID: 182681,
      countryCode: "SG",
      storeID: "S39",
      createdTime: "00:02.3",
      leaveApplnNumber: 148,
    },
    {
      employeeNumber: "V000149",
      date: "7/25/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "NOT APPLICABLE",
      remarks: "Submitted",
      leaveID: 182686,
      countryCode: "SG",
      storeID: "S39",
      createdTime: "00:02.3",
      leaveApplnNumber: 150,
    },
    {
      employeeNumber: "V000149",
      date: "7/26/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "NOT APPLICABLE",
      remarks: "Submitted",
      leaveID: 182687,
      countryCode: "SG",
      storeID: "S39",
      createdTime: "00:02.3",
      leaveApplnNumber: 150,
    },
    {
      employeeNumber: "V000149",
      date: "7/27/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "NOT APPLICABLE",
      remarks: "Submitted",
      leaveID: 182688,
      countryCode: "SG",
      storeID: "S39",
      createdTime: "00:02.3",
      leaveApplnNumber: 150,
    },
    {
      employeeNumber: "V000149",
      date: "7/29/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "NOT APPLICABLE",
      remarks: "Submitted",
      leaveID: 182689,
      countryCode: "SG",
      storeID: "S39",
      createdTime: "00:02.3",
      leaveApplnNumber: 151,
    },
    {
      employeeNumber: "V000149",
      date: "7/30/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "NOT APPLICABLE",
      remarks: "Submitted",
      leaveID: 182690,
      countryCode: "SG",
      storeID: "S39",
      createdTime: "00:02.3",
      leaveApplnNumber: 151,
    },
    {
      employeeNumber: "V000149",
      date: "7/31/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "NOT APPLICABLE",
      remarks: "Submitted",
      leaveID: 182691,
      countryCode: "SG",
      storeID: "S39",
      createdTime: "00:02.3",
      leaveApplnNumber: 152,
    },
    {
      employeeNumber: "V000180",
      date: "6/15/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "NOT APPLICABLE",
      remarks: null,
      leaveID: 140491,
      countryCode: "MY",
      storeID: "L87",
      createdTime: "40:59.0",
      leaveApplnNumber: 279,
    },
    {
      employeeNumber: "V000180",
      date: "7/27/2025",
      leaveTypeCode: "LVANL",
      leaveUnits: 1,
      leaveTypeLongDescription: "Annual Leave",
      leaveReason: "VACATION",
      remarks: "Submitted",
      leaveID: 179562,
      countryCode: "MY",
      storeID: "L87",
      createdTime: "00:02.3",
      leaveApplnNumber: 280,
    },
  ],
  storeTargets: [
    {
      id: 1,
      brandId: 5,
      storeId: 1,
      year: 2024,
      month: 10,
      roleId: "role-manager",
      targetAmount: 50000.0,
      storeKPITargetBraPenetration: 75.0,
      storeKPIAchievementBraPenetration: 70.0,
      storeTargetAchievement: 85.5,
      status: 1,
    },
    {
      id: 2,
      brandId: 5,
      storeId: 1,
      year: 2024,
      month: 10,
      roleId: "role-associate",
      targetAmount: 25000.0,
      storeKPITargetBraPenetration: 60.0,
      storeKPIAchievementBraPenetration: 65.0,
      storeTargetAchievement: 90.0,
      status: 1,
    },
  ],
};

const testDataSlice = createSlice({
  name: "testData",
  initialState,
  reducers: {
    updateBasicInfo: (
      state,
      action: PayloadAction<{ year?: number; month?: number; storeId?: number }>
    ) => {
      if (action.payload.year !== undefined) state.year = action.payload.year;
      if (action.payload.month !== undefined)
        state.month = action.payload.month;
      if (action.payload.storeId !== undefined)
        state.storeId = action.payload.storeId;
    },
    updateUser: (
      state,
      action: PayloadAction<{ index: number; user: Partial<User> }>
    ) => {
      const { index, user } = action.payload;
      if (index >= 0 && index < state.users.length) {
        state.users[index] = { ...state.users[index], ...user };
      }
    },
    addUser: (state, action: PayloadAction<User>) => {
      state.users.push(action.payload);
    },
    removeUser: (state, action: PayloadAction<number>) => {
      state.users.splice(action.payload, 1);
    },
    updateSale: (
      state,
      action: PayloadAction<{ index: number; sale: Partial<Sale> }>
    ) => {
      const { index, sale } = action.payload;
      if (index >= 0 && index < state.sales.length) {
        state.sales[index] = { ...state.sales[index], ...sale };
      }
    },
    addSale: (state, action: PayloadAction<Sale>) => {
      state.sales.push(action.payload);
    },
    removeSale: (state, action: PayloadAction<number>) => {
      state.sales.splice(action.payload, 1);
    },
    updateAttendance: (
      state,
      action: PayloadAction<{ index: number; attendance: Partial<Attendance> }>
    ) => {
      const { index, attendance } = action.payload;
      if (index >= 0 && index < state.attendance.length) {
        state.attendance[index] = { ...state.attendance[index], ...attendance };
      }
    },
    addAttendance: (state, action: PayloadAction<Attendance>) => {
      state.attendance.push(action.payload);
    },
    removeAttendance: (state, action: PayloadAction<number>) => {
      state.attendance.splice(action.payload, 1);
    },
    updateLeave: (
      state,
      action: PayloadAction<{ index: number; leave: Partial<Leave> }>
    ) => {
      const { index, leave } = action.payload;
      if (index >= 0 && index < state.leaves.length) {
        state.leaves[index] = { ...state.leaves[index], ...leave };
      }
    },
    addLeave: (state, action: PayloadAction<Leave>) => {
      state.leaves.push(action.payload);
    },
    removeLeave: (state, action: PayloadAction<number>) => {
      state.leaves.splice(action.payload, 1);
    },
    updateStoreTarget: (
      state,
      action: PayloadAction<{
        index: number;
        storeTarget: Partial<StoreTarget>;
      }>
    ) => {
      const { index, storeTarget } = action.payload;
      if (index >= 0 && index < state.storeTargets.length) {
        state.storeTargets[index] = {
          ...state.storeTargets[index],
          ...storeTarget,
        };
      }
    },
    addStoreTarget: (state, action: PayloadAction<StoreTarget>) => {
      state.storeTargets.push(action.payload);
    },
    removeStoreTarget: (state, action: PayloadAction<number>) => {
      state.storeTargets.splice(action.payload, 1);
    },
    resetTestData: () => initialState,
    updateWorkflowJson: (state, action: PayloadAction<string>) => {
      state.workflowJson = action.payload;
    },
  },
});

export const {
  updateBasicInfo,
  updateUser,
  addUser,
  removeUser,
  updateSale,
  addSale,
  removeSale,
  updateAttendance,
  addAttendance,
  removeAttendance,
  updateLeave,
  addLeave,
  removeLeave,
  updateStoreTarget,
  addStoreTarget,
  removeStoreTarget,
  resetTestData,
  updateWorkflowJson,
} = testDataSlice.actions;

export default testDataSlice.reducer;
